upload Personal data from server
IT-Academy-Social-Projects-KRV/EasyCA-Angular pull request #12
Opened 2021-09-01 11:09 UTC by pinkevmladchy

2021-09-01 16:07 UTC, LizaShemetovska requested changes

2021-09-01 16:07 UTC, LizaShemetovska commented on src/app/components/personal-cabinet/personal-cabinet.component.css
>  }
Add new line

2021-09-01 16:07 UTC, LizaShemetovska commented on src/app/components/personal-cabinet/personal-cabinet.ts
>  }
Add new line

2021-09-01 16:07 UTC, LizaShemetovska commented on src/app/models/driverLicence.ts
> +}
Add new line

2021-09-02 09:10 UTC, NerevitVasyan commented on src/app/models/adress.ts
> +        public PostalCode:string
add space after :

2021-09-02 09:10 UTC, NerevitVasyan commented on src/app/components/personal-cabinet/personal-cabinet.ts
> +  public personalData: any;
please, try to use models for this

2021-09-02 09:10 UTC, NerevitVasyan commented on src/app/components/personal-cabinet/personal-cabinet.ts
> +  public userName: null;
specify type, i suppose here should be string

2021-09-02 10:24 UTC, vladtymo approved these changes

2021-09-02 10:29 UTC, NerevitVasyan approved these changes

2021-09-02 10:33 UTC, LizaShemetovska approved these changes

2021-09-02 10:33 UTC, LizaShemetovska commented on src/app/components/personal-cabinet/personal-cabinet.component.html
> +              <h1><span>Birthday:</span>{{this.personalData.birthDay}}</h1>
Need to use elements from Ant design

2021-09-02 10:34 UTC, merged