all quastion to Dima
IT-Academy-Social-Projects-KRV/EasyCA-Angular pull request #14
Opened 2021-09-02 20:39 UTC by zharan96prog

2021-09-03 07:33 UTC, LizaShemetovska requested changes

2021-09-03 07:33 UTC, LizaShemetovska commented on src/app/components/transport/transport.ts
> +      console.log(data);
Delete console.log

2021-09-03 07:33 UTC, LizaShemetovska commented on src/app/models/Transport.ts
> +        public insuarenceNumber: string,
InsuaranceNumber is object

2021-09-03 07:33 UTC, LizaShemetovska commented on src/app/models/Insuarance.ts
> +        public id: string,
This is object, so it doesn't id

2021-09-03 12:46 UTC, pinkevmladchy approved these changes
good work

2021-09-06 13:24 UTC, NerevitVasyan approved these changes

2021-09-06 17:36 UTC, merged