Create UI and logic for Violation List
IT-Academy-Social-Projects-KRV/EasyCA-Angular pull request #29
Opened 2021-09-24 14:23 UTC by ICHTLAY

2021-09-26 14:25 UTC, SashaKorniichuk requested changes

2021-09-26 14:25 UTC, SashaKorniichuk commented on src/app/components/violation-list/violation-list.component.ts
> +        console.log(data);
delete console.log

2021-09-26 14:25 UTC, SashaKorniichuk commented on src/app/components/violation-list/violation-list.component.ts
> +        console.log(err.error.message);
delete console.log and display error in UI (toastr)

2021-09-29 10:38 UTC, merged

2021-09-29 10:38 UTC, vladtymo approved these changes