#132 Create an Admin Panel
IT-Academy-Social-Projects-KRV/EasyCA-Angular pull request #38
Opened 2021-10-05 14:23 UTC by pinkevmladchy

2021-10-10 13:01 UTC, ICHTLAY requested changes

2021-10-10 13:01 UTC, ICHTLAY commented on src/app/components/list-ca/list-ca.component.html
> +                <tr class="mainName" >
Why you dont get CAs from backend but set a hardcoded template?

2021-10-10 13:01 UTC, ICHTLAY commented on src/app/components/list-inspector/list-inspector.component.html
> +                <tr (click)="showModalEdit()" class="mainName">
Why you dont get inspetors from backend but set a hardcoded template?

2021-10-11 10:49 UTC, SashaKorniichuk approved these changes

2021-10-11 10:51 UTC, ICHTLAY approved these changes

2021-10-11 10:52 UTC, merged