#158 create logic for view ca
IT-Academy-Social-Projects-KRV/EasyCA-Angular pull request #50
Opened 2021-10-25 17:02 UTC by pinkevmladchy

2021-10-25 19:16 UTC, SashaKorniichuk requested changes

2021-10-25 19:16 UTC, SashaKorniichuk commented on src/app/components/inspector/view-ca-modal/view-ca.component.ts
> +        phoneNumber: selectedRecord.witnesses[0].phoneNumber,
Create let witness and use witness.firstname...

2021-10-25 19:16 UTC, SashaKorniichuk commented on src/app/components/inspector/view-ca-modal/view-ca.component.ts
> +        transportId: selectedRecord.sideOfAccident.transportId,
Create let sideOfAccident and use sideOfAccident.email...

2021-10-25 19:16 UTC, SashaKorniichuk commented on src/app/components/inspector/view-ca-modal/view-ca.component.ts
> +        crossStreet: selectedRecord.address.crossStreet,
Create let address and use address.city..

2021-10-25 19:16 UTC, SashaKorniichuk commented on src/app/components/inspector/view-ca-modal/view-ca.component.ts
> +          console.log(this.transportForm.value);
delete

2021-10-25 19:16 UTC, SashaKorniichuk commented on src/app/components/inspector/view-ca-modal/view-ca.component.ts
> +        if(this.protocolCA){
use condition isAdd&&protocolCA

2021-10-25 19:16 UTC, SashaKorniichuk commented on src/app/components/inspector/view-ca-modal/view-ca.component.ts
> +  isAdd = false;
add public

2021-10-25 19:16 UTC, SashaKorniichuk commented on src/app/components/inspector/view-ca-modal/view-ca.component.ts
> +  protocolCA: CarAccident;
add public

2021-10-25 19:16 UTC, SashaKorniichuk commented on src/app/components/inspector/inspector-list-of-car-accidents/inspector-list-of-car-accidents.component.ts
>        error => { }
add toastr if list empty using error.err.message

2021-10-27 18:48 UTC, SashaKorniichuk approved these changes

2021-10-28 10:01 UTC, ICHTLAY approved these changes

2021-10-28 10:52 UTC, merged