#163 create logic to update protocol by inspector
IT-Academy-Social-Projects-KRV/EasyCA-Angular pull request #53
Opened 2021-10-29 11:14 UTC by pinkevmladchy

2021-10-29 11:44 UTC, swem-st approved these changes

2021-10-29 20:36 UTC, ICHTLAY approved these changes

2021-11-01 15:43 UTC, SashaKorniichuk requested changes

2021-11-01 15:43 UTC, SashaKorniichuk commented on src/app/components/inspector/inspector-list-of-car-accidents/inspector-list-of-car-accidents.component.ts
> +  method(){
rename this function

2021-11-02 10:54 UTC, SashaKorniichuk approved these changes

2021-11-02 10:55 UTC, merged