Created Login Logic on Frontend
IT-Academy-Social-Projects-KRV/EasyCA-Angular pull request #7
Opened 2021-08-30 11:43 UTC by LizaShemetovska

2021-08-30 16:52 UTC, SashaKorniichuk approved these changes

2021-08-30 18:04 UTC, swem-st approved these changes

2021-08-31 12:10 UTC, NerevitVasyan requested changes

2021-08-31 12:10 UTC, NerevitVasyan commented on src/app/helpers/jwt.interceptor.ts
> +               Authorization: "Bearer" + token,
We need a space between Bearer and token
It would be better to write: \`Bearer ${token}\`

2021-08-31 12:10 UTC, NerevitVasyan commented on src/app/services/account.service.ts
> +    let authToken = this.tokenStorageService.getToken();
const

2021-08-31 12:10 UTC, NerevitVasyan commented on src/app/components/login-form/login-form.component.css
>  }
please add new line at the end of file

2021-08-31 12:10 UTC, NerevitVasyan commented on src/app/helpers/jwt.interceptor.ts
> +];
add new line

2021-08-31 12:10 UTC, NerevitVasyan commented on src/app/components/login-form/login-form.component.ts
> +  form: any = {
It would be better to use FormControl here

2021-08-31 15:09 UTC, NerevitVasyan approved these changes

2021-08-31 15:15 UTC, merged